services:
  - type: web
    name: ai-chatbot-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGSMITH_PROJECT
        sync: false

  - type: web
    name: ai-chatbot-frontend
    env: python
    buildCommand: pip install streamlit requests
    startCommand: streamlit run frontend/app.py --server.port 10000 --server.address 0.0.0.0 --server.headless true